#!/bin/bash
set -eux

# example of my post start script
# TODO I guess ideally this would be a separate docker build step?

# apparently that can't be added to docker-compose file :( https://github.com/docker/compose/issues/1809

docker exec cloudmacs sh -c 'apk add xclip git'

RG_VERSION=11.0.2
docker exec cloudmacs sh -c "wget https://github.com/BurntSushi/ripgrep/releases/download/${RG_VERSION}/ripgrep-${RG_VERSION}-x86_64-unknown-linux-musl.tar.gz && tar xzf ripgrep-${RG_VERSION}-x86_64-unknown-linux-musl.tar.gz && mv ripgrep-${RG_VERSION}-x86_64-unknown-linux-musl/rg /usr/local/bin"
